Search rooms
PSW-LEVI-FIVE/Intranet-App pull request #32
Opened 2022-11-28 17:57 UTC by cikii555

2022-11-28 18:08 UTC, JanosevicRa177 requested changes

2022-11-28 18:08 UTC, JanosevicRa177 commented on src/app/manager/hospital-map/hospital-map.module.ts
> +
remove spaces

2022-11-28 18:08 UTC, JanosevicRa177 commented on src/app/manager/hospital-map/hospital-map.module.ts
> +
remove spaces

2022-11-28 18:08 UTC, JanosevicRa177 commented on src/app/app.module.ts
> +
remove spaces

2022-11-28 18:08 UTC, JanosevicRa177 commented on src/app/manager/hospital-map/model/room.model.ts
> +        type: number
create frontend enum

2022-11-28 18:08 UTC, JanosevicRa177 commented on src/app/manager/hospital-map/search-rooms/search-rooms.component.ts
> +
remove spaces

2022-11-28 18:08 UTC, JanosevicRa177 commented on src/app/manager/hospital-map/services/room-map.service.ts
> +  } */
remove comments

2022-11-28 18:08 UTC, JanosevicRa177 commented on src/app/material/material.module.ts
> +
remove spaces

2022-11-28 18:08 UTC, JanosevicRa177 commented on src/app/material/material.module.ts
> +
remove spaces

2022-11-28 18:08 UTC, JanosevicRa177 commented on src/app/modules/hospital-map/floor-map/floor-map.component.ts
> +    //this.clickInfo = this.floorMapService.onClickShowName(this.svg,this.data)
remove comments

2022-11-28 18:08 UTC, JanosevicRa177 commented on src/app/modules/hospital-map/floor-map/floor-map.component.ts
> +  //constructor(private floorMapService: FloorMapService, private buildingMapService:BuildingMapService, private router:Router) { }
remove

2022-11-28 18:08 UTC, JanosevicRa177 commented on src/app/modules/hospital-map/room-map/room-map.component.css
> +}*/
remove

2022-11-28 18:08 UTC, JanosevicRa177 commented on src/app/modules/hospital-map/room-map/room-map.component.html
> +   </body>-->
remove

2022-11-28 18:08 UTC, JanosevicRa177 commented on src/app/modules/hospital-map/services/building-map.service.ts
> +  // }
remove

2022-11-28 18:08 UTC, JanosevicRa177 commented on src/app/modules/hospital-map/services/floor-map.service.ts
> +  // }
remove

2022-11-28 18:08 UTC, JanosevicRa177 commented on src/app/modules/hospital-map/services/room-map.service.ts
> +  // }
remove

2022-11-28 18:08 UTC, JanosevicRa177 commented on src/app/modules/hospital-map/room-map/room-map.component.ts
> +  // this.roomMapService.updateRoom(this.selectedRoom);
remove

2022-11-28 18:08 UTC, JanosevicRa177 commented on src/app/modules/hospital-map/floor-map/floor-map.component.ts
> +    // this.floorMapService.updateFloor(this.selectedFloor);
remove if not needed

2022-11-28 18:08 UTC, JanosevicRa177 commented on src/app/modules/hospital-map/building-map/building-map.component.ts
> +
remove spaces and comment

2022-11-28 18:08 UTC, JanosevicRa177 commented on src/app/modules/hospital-map/building-map/building-map.component.ts
> +  public selectedBuildingId:any;
dont use any if you dont need to

2022-11-28 18:08 UTC, JanosevicRa177 commented on src/app/modules/hospital-map/building-map/building-map.component.css
> +   justify-content: center
remove commented css

2022-11-28 18:08 UTC, JanosevicRa177 commented on src/app/manager/hospital-map/search-rooms/search-rooms.component.ts
> +
remove spaces

2022-11-28 18:08 UTC, JanosevicRa177 commented on src/app/manager/hospital-map/search-rooms/search-rooms.component.css
> +
remove spaces

2022-11-28 18:08 UTC, JanosevicRa177 commented on src/app/manager/hospital-map/room-map/room-map.component.ts
> +    //console.log(this.id+"caoooo")
remove comment

2022-11-28 18:08 UTC, JanosevicRa177 commented on src/app/manager/hospital-map/building-map/building-map.component.ts
> +      console.log(this.buildings)
remove console.log

2022-11-28 18:08 UTC, JanosevicRa177 commented on src/app/modules/hospital-map/floor-map/floor-map.component.css
> +}
remove commented css

2022-11-28 18:08 UTC, JanosevicRa177 commented on src/app/modules/hospital-map/room-map/room-map.component.css
> +}
remove commented css

2022-11-28 18:08 UTC, JanosevicRa177 commented on src/app/modules/hospital-map/services/floor-map.service.ts
> +
remove unnecessary spaces

2022-11-30 18:14 UTC, srdjan1210 commented on src/app/manager/hospital-map/room-map/room-map.component.css
>  .rightSide{
Html classes should follow naming convention something-something-something

2022-11-30 18:14 UTC, srdjan1210 commented on src/app/modules/hospital-map/services/building-map.service.ts
> +    .attr("x", function(d:any){ return d.xCoordinate })
Instead of using function(parametar) { return ...}, you can use (parameter) => ...

2022-11-30 18:14 UTC, srdjan1210 commented on src/app/modules/hospital-map/services/floor-map.service.ts
> +    .attr("y", function(d:any){ return d.yCoordinate})
Same thing here

2022-11-30 18:14 UTC, srdjan1210 commented on src/app/modules/hospital-map/services/room-map.service.ts
> +    .attr("y", function(d:any){ return d.yCoordinate})
Same thing here

2022-11-30 21:47 UTC, JanosevicRa177 approved these changes

2022-12-01 14:04 UTC, merged